In [1]:
#import data analytics libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import pickle

In [2]:
#read in the dataset
dataset = pd.read_csv('outwx_fine_cleaned21.csv')
dataset.head()

,ID,Lat,Lng,OutTime,Temp,Precip,WindSpd,WindGust,Press,Humid,Dew,Outage
0,0,-0.569174,34.862274,08/02/2021 17:00,26,4.2,5,5,1008,43,12,0
1,1,0.059492,34.285599,13/11/2020 08:00,21,0.7,7,10,1015,71,15,0
2,2,-1.267577,36.842441,14/04/2021 17:00,21,0.7,12,18,1012,72,15,0
3,3,-1.307644,36.778698,22/12/2020 09:00,20,0.0,18,21,1017,57,12,0
4,4,-1.037109,36.920895,03/04/2021 04:00,16,0.2,4,6,1015,95,15,0

In [3]:
# describing the dataset(mean, count, std dev, percentiles etc...)
dataset.describe(include='all')

,ID,Lat,Lng,OutTime,Temp,Precip,WindSpd,WindGust,Press,Humid,Dew,Outage
count,270152.000000,270152.000000,270152.000000,270152,270152.000000,270152.000000,270152.000000,270152.000000,270152.000000,270152.000000,270152.000000,270152.000000
unique,NaN,NaN,NaN,22276,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,13/05/2020 15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,135075.500000,-1.183763,36.766015,NaN,20.169186,0.524055,10.961392,15.573203,1013.932227,69.929499,13.733765,0.040096
std,77986.309298,0.869119,1.019543,NaN,3.987640,2.306747,5.959513,9.144710,2.666514,18.017628,3.202991,0.196185
min,0.000000,-4.644477,33.976040,NaN,4.000000,0.000000,0.000000,0.000000,1003.000000,11.000000,-8.000000,0.000000
25%,67537.750000,-1.304534,36.714561,NaN,17.000000,0.000000,6.000000,9.000000,1012.000000,57.000000,12.000000,0.000000
50%,135075.500000,-1.253145,36.822781,NaN,20.000000,0.000000,10.000000,14.000000,1014.000000,73.000000,14.000000,0.000000
75%,202613.250000,-1.140089,36.919720,NaN,23.000000,0.100000,15.000000,21.000000,1016.000000,85.000000,15.000000,0.000000
max,270151.000000,4.398081,40.901901,NaN,37.000000,20.500000,45.000000,66.000000,1022.000000,100.000000,25.000000,1.000000

In [4]:
#rermoving "OutTime, ID, Lat & Lng" since they are no longer needed in this context
del dataset['OutTime']
del dataset['ID']

del dataset['Lat']
del dataset['Lng']

dataset.head()

   Temp  Precip  WindSpd  WindGust  Press  Humid  Dew  Outage
0    26     4.2        5         5   1008     43   12       0
1    21     0.7        7        10   1015     71   15       0
2    21     0.7       12        18   1012     72   15       0
3    20     0.0       18        21   1017     57   12       0
4    16     0.2        4         6   1015     95   15       0

In [5]:
#deleting "WindSpd" and "Dew" since they do not heavily correlate to th dataset
del dataset['WindSpd']
del dataset['Dew']

dataset.head()

   Temp  Precip  WindGust  Press  Humid  Outage
0    26     4.2         5   1008     43       0
1    21     0.7        10   1015     71       0
2    21     0.7        18   1012     72       0
3    20     0.0        21   1017     57       0
4    16     0.2         6   1015     95       0

In [6]:
# creating input features and target variables
X= dataset.iloc[:,0:5]
y= dataset.iloc[:,5]

X.head()

   Temp  Precip  WindGust  Press  Humid
0    26     4.2         5   1008     43
1    21     0.7        10   1015     71
2    21     0.7        18   1012     72
3    20     0.0        21   1017     57
4    16     0.2         6   1015     95

In [7]:
# #standardizing the input feature
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
X
y.tail()

270147    0
270148    0
270149    0
270150    1
270151    0
Name: Outage, dtype: int64

In [8]:
# Multinomial Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB

# Import Tf-idf Vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

# Import the Label Encoder
from sklearn.preprocessing import LabelEncoder

# Import the train test split
from sklearn.model_selection import train_test_split

# To evaluate our model
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import roc_auc_score

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=34)

In [10]:
# Initialize the Multinomial Naive Bayes classifier
nb = MultinomialNB()

# Fit the model
nb = nb.fit(X_train, y_train)

# Print the accuracy score
print("Accuracy:",nb.score(X_test, y_test))

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-93972214ae1e>", line 5, in <module>
    nb = nb.fit(X_train, y_train)
  File "C:\Anaconda\lib\site-packages\sklearn\naive_bayes.py", line 638, in fit
    self._count(X, Y)
  File "C:\Anaconda\lib\site-packages\sklearn\naive_bayes.py", line 771, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "C:\Anaconda\lib\site-packages\sklearn\utils\validation.py", line 1068, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2061, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'ValueError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\IPython\core\ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "C:\Anaconda\lib\site-packages\IPython\core\ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
  File "C:\Anaconda\lib\site-packages\IPython\core\ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "C:\Anaconda\lib\inspect.py", line 1503, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "C:\Anaconda\lib\inspect.py", line 1461, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "C:\Anaconda\lib\inspect.py", line 708, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "C:\Anaconda\lib\inspect.py", line 754, in getmodule
    os.path.realpath(f)] = module.__name__
  File "C:\Anaconda\lib\ntpath.py", line 664, in realpath
    if _getfinalpathname(spath) == path:
KeyboardInterrupt

TypeError: object of type 'NoneType' has no len()

In [ ]:
# Predict the labels
y_pred = nb.predict(X_test)

# Print the Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix\n")
print(cm)

# Print the Classification Report
cr = classification_report(y_test, y_pred)
print("\n\nClassification Report\n")
print(cr)

In [ ]:
#passing a Numpy array of test weather variables and seeing the probabilities produced. 
a= np.array([[24.0,5.0,9.0,1010.0,52.0],[16.0,2.0,8.0,1015.0,95.0]])
print(nb.predict(a))